---
dist: xenial
sudo: required
language: python
python: "3.7"

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-toolkit daixijun.toolkit
  - cd daixijun.toolkit

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
