---
# tasks file for daixijun.toolkit
- name: Install common tools
  package:
    name: "{{ toolkit_common_packages | union(toolkit_packages) }}"
    update_cache: yes
    state: present
  register: toolkit_install_tools
  async: 300
  poll: 0
  changed_when: False
  when:
    - not ansible_check_mode

- name: Wait for install complete
  async_status:
    jid: "{{ toolkit_install_tools.ansible_job_id }}"
  register: toolkit_install_tools_status
  until: toolkit_install_tools_status.finished
  retries: 60
  when:
    - not ansible_check_mode
